### ISSUE TITLE
Question related to ASMDEF

### ISSUE THREAD

**Issue by MostHated** [baba-s/UniEnumUtils#1]
Hello, 
I use an asset called [Auto-ASMDEF](https://assetstore.unity.com/packages/tools/utilities/auto-asmdef-156502) which, as the name suggests, lets you automatically create assembly definition files for the things in your project by selecting which folders you do or do not want to be included. For some reason though, when I run the ASMDEF process and it creates them, the EnumUtils package becomes inaccessible (namespace Kogane cannot be found), but other packages of yours that I am also using at the same time, such as your Scope package, do not have any issue and work perfectly. 

Is there anything different about this package vs. the Scope package that you know of that might keep it from working while the other works fine? 

Thanks!
-MH

**Comment by baba-s** [comment]
@MostHated 

> Is there anything different about this package vs. the Scope package that you know of that might keep it from working while the other works fine?

Hmmm, this package is made the same way as the other packages. :thinking: 

* Is the .asmdef "Auto Referenced" turned on?  
* Does the code editor successfully load the .asmdef?

**Comment by MostHated** [comment]
You are absolutely correct, for some reason when I ran autoASMDEF it selected all of the packages except that one. >_< My apologies. I am fairly new to assembly definitions in general, so I didn't think to check that. I will be sure to remember going forward. 

Thanks!
-MH
